[tool.poetry]
name = "qpc"
version = "1.0.1"
description = ""
authors = ["QPC Team <quipucords@redhat.com>"]
license = "GPLv3"
exclude = [
    "**/test_*.py",
    "**/*_tests.py",
    "**/tests_*.py",
]

[tool.poetry.scripts]
dsc = 'qpc.__main__:main'

[tool.poetry.dependencies]
python = "^3.7"
requests = ">=2.28.1"
cryptography = ">=37.0.4"

[tool.poetry.dev-dependencies]
coverage = ">=6.4.2"
black = ">=22.6.0"
darker = ">=1.5.0"
flake8 = "*"
flake8-docstrings = ">=1.6.0"
flake8-quotes = ">=3.3.1"
flakeheaven = ">=1.0.0"
isort = ">=5.10.1"
pylint = [
    {version = "~2.13", python = "~3.7"},
    {version = ">=2.14", python = "^3.8"}
]
pylint-pytest = ">=1.1.2"
pytest = ">=7.1.2"
pytest-cov = ">=3.0.0"
pytest-lazy-fixture = ">=0.6.3"
requests-mock = ">=1.9.3"
tox = ">=3.25.1"
tox-poetry = ">=0.4.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.darker]
revision = "3b5eec564b42ab8f4c152a93144dae33e85bc175"
isort = true

[tool.flakeheaven]
base = "https://raw.githubusercontent.com/quipucords/linting/main/base-flakeheaven.toml"
baseline = ".flakeheaven-baseline"

[tool.isort]
profile = "black"
known_first_party = ["qpc"]

[tool.pylint.master]
load-plugins = ["pylint_pytest"]

[tool.pytest.ini_options]
pythonpath = "qpc"
python_files = [
    "tests.py",
    "test_*.py",
    "*_tests.py",
    "tests_*.py",
]
